spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-tangjunlin-dev2这个是测试的的
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-tangjunlin-test2这个是我测试的的
#  请保存为UTF-8格式
 
 

