spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-tangjunlin-dev2-ttt
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-tangjunlin-test2-ttt
#  请保存为UTF-8格式
 
 

